import type { Metadata } from "next";
import "./globals.css";

import { Catamaran } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

const catamaran = Catamaran({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-catamaran",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" className={`${catamaran.variable} `}>
      <body>
        <Header /> {/* Füge den Header hier hinzu */}
        {children}
        <Footer /> {/* Füge den Footer hier hinzu */}
      </body>
    </html>
  );
}
