import type { Metadata } from "next";
import "./globals.css";

import { Catamaran } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";
import Script from "next/script";

const catamaran = Catamaran({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-catamaran",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" className={`${catamaran.variable} `}>
      <Script
        id="_etLoader"
        type="text/javascript"
        data-block-cookies="true"
        data-secure-code="i9strK"
        data-page-changed-detection="url"
        src="//code.etracker.com/code/e.js"
        async
      />
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
